M48
; DRILL file {KiCad 8.0.8-8.0.8-0~ubuntu24.04.1} date 2025-04-29T16:21:52-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-04-29T16:21:52-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8-8.0.8-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X4.7494Y-4.2636
X4.977Y-4.2636
M30
